### ISSUE TITLE
Missing jar files in v1.3.1 release

### ISSUE THREAD

**Issue by nicolaspayette** [cstaelin/Stats-Extension#2]
No binaries are currently available from:
https://github.com/cstaelin/Stats-Extension/releases/tag/v1.3.1

See:
http://stackoverflow.com/questions/29616944/stats-extension-no-stats-jar-file

**Comment by cstaelin** [comment]
Fixed in v1.3.2.

**Comment by nicolaspayette** [comment]
Thanks for taking care of this! Note, however, that committing the jar files to your repo is not ideal. As shown in https://github.com/blog/1547-release-your-software, you can attach binaries to your releases:

![screenshot](https://camo.githubusercontent.com/63e25ab0df8956e54ffc5822c7508a6e428b7b62/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f32312f3733373937352f62393837656136322d653333622d313165322d393332622d3335366437356338363338352e6a7067)

The best practice is to upload a separate zip file with only what the users need (in most cases: only the jars).

**Comment by cstaelin** [comment]
Thanks Nicolas.  I'm still learning this release stuff, and slowly!  I have
an upcoming addition to the extension and I'll make that change when I
publish it.

Best,
Charles

---

Charles P. Staelin
Professor and chair, Department of Economics
Director, Global South Development Program
Smith College
Northampton, MA 01063
